options:
  max_fps: 60
  show_ip: Yes
  show_update: Yes
  fullscreen: Yes
  resolution: "0,0"
  sort_items_alphanum: True
  sort_items_with_roms_first: True
  hide_system_tools: False
  show_cursor: No
  allow_quit_to_console: True
  use_scene_transitions: Yes
  theme_pack: "default"
  default_music_volume: 0.2

scraper_options:
  show_clones: no
  overwrite_images: no

menu_items:
  - label: SNES
    visible: Yes
    roms: /home/pi/pimame/roms/snes/
    full_path: yes
    extension: yes
    override_menu: no
    command: /home/pi/pimame/emulators/pisnes/snes9x

  - label: MAME4All
    visible: No
    roms: /home/pi/pimame/roms/mame4all/
    full_path: no
    override_menu: no
    command: /home/pi/pimame/emulators/mame4all-pi/mame 

  - label: Neo Geo
    visible: Yes
    roms: /home/pi/pimame/roms/neogeo/
    full_path: yes
    extension: yes
    command: /home/pi/pimame/emulators/fba/fba2x --config=/home/pi/pimame/neogeo.cfg 

  - label: AdvMAME
    visible: No
    roms: /home/pi/pimame/roms/advmame/
    full_path: no
    command: advmame 

  - label: Final Burn
    visible: Yes
    roms: /home/pi/pimame/roms/pifba/
    full_path: yes
    extension: yes
    override_menu: no
    command: /home/pi/pimame/emulators/fba/fba2x --config=/home/pi/pimame/arcade.cfg  

  - label: Genesis
    visible: Yes
    roms: /home/pi/pimame/roms/genesis/
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/dgen-sdl-1.32/dgen

  - label: NES
    visible: Yes
    roms: /home/pi/pimame/roms/nes/
    full_path: yes
    extension: yes
    command: /home/pi/pimame/emulators/fceux/fceux

  - label: Atari 2600
    visible: Yes
    full_path: no
    command: stella
    roms: /home/pi/pimame/roms/2600/
    override_menu: yes
    type: FRONTEND

  - label: Playstation 1
    visible: Yes
    full_path: no
    command: cd /home/pi/pimame/emulators/pcsx_rearmed && ./pcsx
    override_menu: yes
    roms: /home/pi/pimame/roms/psx/
    type: FRONTEND

  - label: Commodore 64
    visible: Yes
    roms: /home/pi/pimame/roms/c64/
    full_path: no
    override_menu: yes
    command: x64
    type: FRONTEND

  - label: ScummVM
    visible: Yes
    full_path: no
    command: scummvm
    override_menu: yes
    roms: /home/pi/pimame/roms/scummvm/
    type: FRONTEND

  - label: Gameboy
    visible: Yes
    roms: /home/pi/pimame/roms/gb/
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/mednafen/src/mednafen

  - label: Gameboy Advance
    visible: yes
    full_path: yes
    extension: yes
    command: /home/pi/pimame/emulators/gpsp/gpsp
    override_menu: yes
    roms: /home/pi/pimame/roms/gba/

  - label: TurboGrafx 16
    visible: Yes
    roms: /home/pi/pimame/roms/tg16
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/mednafen/src/mednafen -force_module pce_fast

  - label: Neo Geo Pocket Color
    visible: Yes
    roms: /home/pi/pimame/roms/ngpc
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/mednafen/src/mednafen 

  - label: Sega Master System
    visible: Yes
    roms: /home/pi/pimame/roms/sms
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/mednafen/src/mednafen 

  - label: Game Gear
    visible: Yes
    roms: /home/pi/pimame/roms/gg
    full_path: yes
    extension: yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && /home/pi/pimame/emulators/mednafen/src/mednafen 

  - label: ZX Spectrum
    visible: Yes
    full_path: no
    roms: /home/pi/pimame/roms/zxspectrum
    override_menu: Yes
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && cd /home/pi/pimame/emulators/usp_0.0.43/ && ./unreal_speccy_portable && cd /home/pi/pimame/pimame-menu
    type: FRONTEND

  - label: Cave Story
    visible: Yes
    full_path: no
    command: export LD_LIBRARY_PATH=/home/pi/pimame/dispmanx/build/.libs/ && cd /home/pi/pimame/emulators/cavestory_rpi-master && /home/pi/pimame/emulators/cavestory_rpi-master/nx && cd /home/pi/pimame/pimame-menu
    override_menu: yes
    type: GAME

  - label: Restart
    visible: Yes
    full_path: no
    command: sudo reboot
    override_menu: yes
    type: UTILITY

  - label: Shutdown
    visible: Yes
    full_path: no
    command: sudo poweroff
    override_menu: yes
    type: UTILITY

  - label: Update PiPlay
    visible: Yes
    full_path: no
    command: wget -O - http://pimame.org/update.sh | bash
    override_menu: yes
    type: UTILITY

  - label: Rom Scraper
    visible: Yes
    full_path: no
    command: python /home/pi/pimame/pimame-menu/scraper/scrape_script.py
    override_menu: yes
    type: UTILITY

  - label: Install MAME
    visible: Yes
    full_path: no
    command: python /home/pi/pimame/mame_install.py
    override_menu: yes
    type: UTILITY

  - label: Toggle Xbox Controller
    visible: Yes
    full_path: no
    command: sh /home/pi/pimame/toggle_xbox_controller.sh
    override_menu: yes
    type: UTILITY

  - label: raspi-config
    visible: Yes
    full_path: no
    command: sudo raspi-config
    override_menu: yes
    type: UTILITY

  - label: Wifi Config
    visible: Yes
    full_path: no
    command: /home/pi/pimame/wifi-setup/setup.sh
    override_menu: yes
    type: UTILITY

  - label: Exit
    visible: Yes
    full_path: no
    command: exit_piplay
    override_menu: yes
    type: UTILITY